### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by demidovakatya** [pixelastic/pokemonorbigdata#17]
Hi,

There are no images at http://pixelastic.github.io/pokemonorbigdata/.

(checked in Safari & Google Chrome)

**Comment by pixelastic** [comment]
Hmm, this is weird, I have them displaying correctly on my Chrome here.

Could you send me a screenshot of the network tab with the error?

**Comment by demidovakatya** [comment]
![i 2016-02-14 at 02 55 39](https://cloud.githubusercontent.com/assets/5788652/13030749/7bfbe504-d2c6-11e5-936f-5c7527ea1691.png)

![i 2016-02-14 at 02 57 15](https://cloud.githubusercontent.com/assets/5788652/13030756/b0f2098c-d2c6-11e5-863e-16d95cf9daeb.png)

![i 2016-02-14 at 02 56 42](https://cloud.githubusercontent.com/assets/5788652/13030754/9c394b22-d2c6-11e5-81ad-c84a2f54200c.png)

this is the only type of errors I've got

**Comment by pixelastic** [comment]
Oh I see. The errors you're seeing are coming from [Bootstrap](http://getbootstrap.com/), the framework I'm using for the display. They are using proprietary CSS properties for browser cross-compatibility and the errors you're seeing are for the `filter` property which is not working on Safari and Chrome (this is a Microsoft-only property).

And you don't see the images because there are actually no images to display at that step :). I only display the logo image on the answer.

![image](https://cloud.githubusercontent.com/assets/283419/13034352/2e9d83b8-d333-11e5-9996-7d54e61dae06.png)![image](https://cloud.githubusercontent.com/assets/283419/13034377/cad1fd4a-d333-11e5-817c-24ee814464b3.png)

**Comment by demidovakatya** [comment]
oh. damn, it was stupid. I'm sorry 🤕
thanks!

**Comment by pixelastic** [comment]
No problem, thanks for the report anyway :)
