### ISSUE TITLE
Using big data, Netflix saves $1 billion per year on customer retention.

### ISSUE THREAD

**Issue by wastu01** [pixelastic/pokemonorbigdata#31]
https://twitter.com/elonmusk/status/1535144423352311809?s=20

**Comment by pixelastic** [comment]
Well, I know. There is even a specific message now for people coming to the website from the tweet (only for the web version of Twitter though).

**Comment by pixelastic** [comment]
For posterity, here is what the tweet looks like, and what happens when you click on the link to come to this website.

![image](https://github.com/pixelastic/pokemonorbigdata/assets/283419/1917e39b-a09a-49ea-ac32-a261ed4bc67c)
![image](https://github.com/pixelastic/pokemonorbigdata/assets/283419/a73f7087-4c7e-4828-80a2-39e1800fb6e5)

**Comment by wastu01** [comment]
ok
