### ISSUE TITLE
Pokemon Name Language

### ISSUE THREAD

**Issue by jaredpetersen** [pixelastic/pokemonorbigdata#5]
Some of the Pokemon names given are the Japanese (J) names instead of the English (E) ones. It's fine if the Japanese names are used, but the language used should be consistent.

**Japanese Names Used:**
- Mukubird (J) instead of Staravia (E)
- Crebase (J) instead of Avalugg (E)

**English Names Used:**
- Vulpix (E) instead of Rokon (J)
- Feebas (E) instead of Hinbass (J)

Arbok, the only Pokemon used that was not mentioned above, is valid since the name is the same in Japanese and English.

This is a problem on the original Google Form as well, but should be corrected in your application.

**Comment by pixelastic** [comment]
Hey, thanks for the comment and for taking the time to point that out.

I think we should keep Mukubird and Crebase because they sound like Summingbird and Adabas, thus making the game harder. So to be consistent, we should use Japanese name all along...

I'd rather we keep all the Pokemon names in English (to stay consistent with the language used in the game). As you seem to have a pretty good knowledge of the Pokemon world, could you suggest two Pokemon that could be used to replace Mukubird and Crebase whose name, in English, ends in `-bird` and `-base`?

If there are no valid substitue, I might change all the names to the Japanese versions.

**Comment by http404error** [comment]
Japanese names are pretty unfair. I got a lot of negative feedback when sharing among my Pokemon-playing friends. I don't think close similarity of parts of names is that important compared to the type of word construction, which is already funny and misleading enough.

**Comment by pixelastic** [comment]
I'm not really versed in the Pokemon universe. I'd be happy to change the name to something more appropriate, but I'll need your help in finding the right Pokemon for that.

**Comment by http404error** [comment]
You could use Delibird. Also, I'd add Ledian and Sigilyph, since those sound plausibly like Big Data names. I can't find one with -base, though you could add Couchbase as a Big Data answer.

**Comment by pixelastic** [comment]
I like Delibird. Does it still make sense if I keep the same description than Mukubird? _Delibird flies around forests and fields in search of bug Pokémon. It stay within a huge flock._

I also like Sigilyph, this sounds like it could be a BigData tech. Do you mind helping me in writing the description for it?

**Comment by jaredpetersen** [comment]
I agree with @http404error's suggestion for Delibird, but you cannot use the description as Mukubird as Delibird. It's like comparing a starling to a penguin.

 A possible replacement for Crebase could be [Gorebyss](http://bulbapedia.bulbagarden.net/wiki/Gorebyss_%28Pok%C3%A9mon%29), since they are pronounced somewhat similarly.

Here's a list of all of the Pokemon in English with links to their encyclopedia page: http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number

**Comment by pixelastic** [comment]
I suggest:

## Delibird (instead of Mukubird)

![image](https://cloud.githubusercontent.com/assets/283419/11406207/885da746-93ac-11e5-88c8-6d8dbf885893.png)

> His special power is to go incognito on the 25th of December.

## Gorebyss (instead of Crebase)

![image](https://cloud.githubusercontent.com/assets/283419/11406219/95b8df1e-93ac-11e5-98f9-f9e16793a6c1.png)

> His body is durable enough to withstand high-pressure levels in the deep sea. Do no confuse with HBase, Couchbase, MeshBase, Graphbase or KirbyBase.

How does it sound to you, pokemon experts? :)

**Comment by jaredpetersen** [comment]
The Gorebyss blurb is pretty good, but the Delibird one is a bit weird.

#### Possible alterations

##### Gorebyss

> His body is durable enough to withstand the high-pressure of the deep sea. Do not confuse with HBase, Couchbase, MeshBase, Graphbase or KirbyBase.

##### Delibird

> The 25th of December is his favorite day. [INSERT REFERENCE TO BIG DATA TECH HERE]

**Comment by pixelastic** [comment]
I've made the changed in bcfb2719afa0e223c4514e35948748ad8d4ef34d. I wasn't inspired for the Big Data joke reference, so I left it empty. Most of the Pokemon answer do not have any reference to big data anyway.

Thanks to the both of you!
